allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
overrides:
  "brace-expansion@5.0.8": "5.0.12"
  "esbuild@0.18.20": "0.25.12"
