"use client";

import { BarChart3, CalendarDays, HeartHandshake, Moon, Sun, Umbrella } from "lucide-react";
import { useMemo, useState } from "react";
import { buildPeriodAnalysis, monthRange } from "@/lib/analysis";
import type { Doctor, Holiday, Replacement, ScheduleMonth, Vacation } from "@/lib/types";
import { cn, monthLabel } from "@/lib/utils";

type Tab = "summary" | "equity" | "replacements";

function MetricCard({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Sun }) {
  return <div className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3"><Icon size={16} className="text-[var(--brand)]" /><p className="mt-3 text-xl font-semibold">{value}</p><p className="text-[10px] text-[var(--muted)]">{label}</p></div>;
}

export function AnalysisDashboard({ doctors, schedules, replacements, vacations, holidays }: { doctors: Doctor[]; schedules: ScheduleMonth[]; replacements: Replacement[]; vacations: Vacation[]; holidays: Holiday[] }) {
  const months = useMemo(() => [...schedules].filter((item) => item.status === "published").sort((a, b) => b.id.localeCompare(a.id)), [schedules]);
  const [selectedId, setSelectedId] = useState(months[0]?.id ?? "");
  const [tab, setTab] = useState<Tab>("summary");
  const selected = months.find((month) => month.id === selectedId) ?? months[0];
  const monthly = useMemo(() => selected ? buildPeriodAnalysis({ doctors, schedules, vacations, holidays, ...monthRange(selected.year, selected.month) }) : null, [doctors, holidays, schedules, selected, vacations]);
  const quarterly = useMemo(() => {
    if (!selected) return null;
    const month = selected.month;
    const quarterStart = Math.floor((month - 1) / 3) * 3 + 1;
    return buildPeriodAnalysis({ doctors, schedules, vacations, holidays, start: new Date(selected.year, quarterStart - 1, 1, 12), end: new Date(selected.year, quarterStart + 2, 0, 12) });
  }, [doctors, holidays, schedules, selected, vacations]);
  const activeReplacements = replacements.filter((item) => new Date(`${item.expiresAt}T12:00:00`) >= new Date());

  if (!selected || !monthly || !quarterly) return <div className="rounded-2xl bg-[var(--surface)] p-5">No hay meses publicados para analizar.</div>;
  return <div className="space-y-3">
    <div className="grid gap-2 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--brand)]">Gestión clínica</p><h1 className="text-2xl font-semibold tracking-tight">Análisis</h1></div><div className="flex rounded-xl bg-[var(--surface-soft)] p-0.5">{([ ["summary", "Resumen"], ["equity", "Equidad y carga"], ["replacements", "Reemplazos"] ] as [Tab, string][]).map(([value, label]) => <button key={value} onClick={() => setTab(value)} type="button" className={cn("rounded-lg px-3 py-1.5 text-xs font-medium", tab === value && "bg-[var(--surface)] shadow-sm")}>{label}</button>)}</div><div className="sm:justify-self-end"><select className="rounded-lg border border-[var(--line)] bg-[var(--surface)] px-2.5 py-1.5 text-xs capitalize" value={selected.id} onChange={(event) => setSelectedId(event.target.value)}>{months.map((month) => <option value={month.id} key={month.id}>{monthLabel(month.year, month.month)}</option>)}</select></div></div>
    {tab === "summary" ? <section className="space-y-3"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Turnos del mes" value={monthly.assignments.length} icon={CalendarDays} /><MetricCard label="Turnos de día" value={monthly.assignments.filter((item) => item.kind === "DAY").length} icon={Sun} /><MetricCard label="Turnos de noche" value={monthly.assignments.filter((item) => item.kind === "NIGHT").length} icon={Moon} /><MetricCard label="Días de vacaciones" value={monthly.metrics.reduce((sum, item) => sum + item.vacationDays, 0)} icon={Umbrella} /><MetricCard label="Casillas pendientes" value={monthly.missingSlots} icon={BarChart3} /></div><section className="overflow-x-auto rounded-2xl border border-[var(--line)] bg-[var(--surface)]"><table className="min-w-full text-xs"><thead className="bg-[var(--surface-soft)] text-[var(--muted)]"><tr><th className="px-3 py-2 text-left">Médico</th><th>Turnos</th><th>Día</th><th>Noche</th><th>FDS/Fest.</th><th>Vac.</th><th>Esperado</th><th>Diferencial</th></tr></thead><tbody>{monthly.metrics.sort((a,b) => a.doctor.shortName.localeCompare(b.doctor.shortName)).map((item) => <tr className="border-t border-[var(--line)]" key={item.doctor.id}><th className="px-3 py-2 text-left">{item.doctor.shortName}</th><td className="text-center">{item.total}</td><td className="text-center">{item.day + item.daySpecial}</td><td className="text-center">{item.night + item.nightSpecial}</td><td className="text-center">{item.daySpecial + item.nightSpecial}</td><td className="text-center">{item.vacationDays}</td><td className="text-center">{item.expected.total.toFixed(1)}</td><td className={cn("text-center font-semibold", item.difference > .5 ? "text-amber-600" : item.difference < -.5 ? "text-sky-600" : "text-[var(--brand)]")}>{item.difference > 0 ? "+" : ""}{item.difference.toFixed(1)}</td></tr>)}</tbody></table></section></section> : null}
    {tab === "equity" ? <section className="grid gap-3 lg:grid-cols-2"><section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-3"><h2 className="text-sm font-semibold">Trimestre de {monthLabel(selected.year, selected.month)}</h2><div className="mt-3 space-y-2">{quarterly.metrics.sort((a,b) => b.total - a.total).map((item) => <div key={item.doctor.id}><div className="flex justify-between text-xs"><span>{item.doctor.shortName}</span><span>{item.total} / {item.expected.total.toFixed(1)} esperados</span></div><div className="mt-1 h-2 rounded-full bg-[var(--surface-soft)]"><div className="h-full rounded-full bg-[var(--brand)]" style={{ width: `${Math.min(100, item.expected.total ? (item.total / item.expected.total) * 70 : 0)}%` }} /></div></div>)}</div></section><section className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-3"><h2 className="text-sm font-semibold">Cobertura y rachas</h2><p className="mt-1 text-xs text-[var(--muted)]">{quarterly.missingSlots} casillas sin cubrir en el trimestre.</p><div className="mt-3 divide-y divide-[var(--line)]">{quarterly.metrics.sort((a,b) => b.longestStreak - a.longestStreak).map((item) => <div className="flex justify-between py-2 text-xs" key={item.doctor.id}><span>{item.doctor.shortName}</span><span>{item.longestStreak} días consecutivos · {item.vacationDays} vac.</span></div>)}</div></section></section> : null}
    {tab === "replacements" ? <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Puntos vigentes" value={activeReplacements.reduce((sum, item) => sum + item.points, 0)} icon={HeartHandshake} /><MetricCard label="Voluntarios" value={activeReplacements.filter((item) => item.mode === "voluntary").length} icon={HeartHandshake} /><MetricCard label="Invocados" value={activeReplacements.filter((item) => item.mode === "invoked").length} icon={HeartHandshake} /><MetricCard label="Superhéroes" value={activeReplacements.filter((item) => item.superhero).length} icon={HeartHandshake} /><section className="sm:col-span-2 xl:col-span-4 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-3"><h2 className="text-sm font-semibold">Puntajes vigentes por médico</h2><div className="mt-2 divide-y divide-[var(--line)]">{doctors.filter((doctor) => doctor.active).map((doctor) => { const items = activeReplacements.filter((item) => item.doctorId === doctor.id); return <div className="flex items-center justify-between py-2 text-xs" key={doctor.id}><span>{doctor.shortName}</span><span>{items.length} reemplazos · <strong className="text-[var(--brand)]">+{items.reduce((sum, item) => sum + item.points, 0)}</strong></span></div> })}</div></section></section> : null}
  </div>;
}
